app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

category:
    resource: '@AppBundle/Controller/CategoryController.php'
    type: annotation
    prefix: 'category'